### ISSUE TITLE
Suspension not visible 

### ISSUE THREAD

**Issue by iherveOCSIN** [CARA-ch/pmp-issues#14]
Steps:

1. Open portail patient
2. Select patient CARAPMP004
3. Add a medication
4. Once added, suspend this medication

Results: the medication is not visible in the "Suspend" section

![Image](https://github.com/CARA-ch/pmp-issues/assets/158463876/1f6131c2-7af4-43e8-90b0-5174a767ff4a)

**Comment by sep-proactive** [comment]
Not yet implemented. A definition of "récemment" is expected (for example last 30 days).

**Comment by iherveOCSIN** [comment]
Medication suspended but not visible in the medication plan

**Comment by iherveOCSIN** [comment]
Valider avec CARA pour une échéance

**Comment by qligier** [comment]
Fixed.
