### ISSUE TITLE
CH EMED ch-dosage-1 constraint is broken

### ISSUE THREAD

**Issue by dvribeira** [CARA-ch/pmp-issues#24]
Copied from email:

> **The constraint is broken** in CH EMED, its definition does not do what the description states hence it does not enforce sequence = 1 when using split dosage. I will create an issue to get it fixed in CH EMED, but it is not so trivial as it may seem.
> Once fixed, it should do what it says:
> 
> - If there’s only one dosage (base dosage), it shall not contain the sequence field.
> - If there’s more than one dosage, the base dosage shall contain the sequence field and its value shall be 1.
> 
> Some other constraint definitions affecting dosage might be reviewed as a result to check whether they are broken, or they should be completed/improved to allow proper validation of the dosage slicing.
>  
> Alternatively, we could drop this constraint and just add sequence = 1 as a fixed value constraint for base dosage (i.e. base dosage would always have sequence = 1 whether there’s split dosage or not). @CARA-ch/pmp-coordination Happy to hear all the implementers' opinion on this one before bringing the issue to CH EMED.

**Comment by sep-proactive** [comment]
I agree to always have sequence = 1 for the base dosage, whether ther is split dosage or not.

**Comment by CheriGey** [comment]
Our preference is to just add clarity to the constraint.  Currently, Soarian is using the presence of dosage.Sequence on dosage-1 to indicate whether this is a Split Dose order or not but can make the code change to support this request if necessary.

**Comment by dejajs** [comment]
just implemented in PRESCO: monodose -> no sequence
                                                multidose -> sequence 1, 2, etc
open to change if necessary

**Comment by iherveOCSIN** [comment]
@dvribeira question/proposition de solution envoyée à CH EMED, en attente de réponse de leur part

**Comment by dvribeira** [comment]
https://github.com/hl7ch/ch-emed/issues/263

**Comment by dvribeira** [comment]
The proposed fix for the constraint has been implemented by CH EMED, to be released with its next version (5.0.0) and integrated into CH EMED EPR with its next version (TBD). Since this broken constraint is not blocking, no further steps will be taken on our side.
