### ISSUE TITLE
Dosage or split dosage CH EMED

### ISSUE THREAD

**Issue by iherveOCSIN** [CARA-ch/pmp-issues#26]
A decision must be made with the current integrators : whether using the simple dosage as describe in the CH EMED guide or not.

More info in the message of @dvribeira below

"Pas un bug, mais Presco (et je crois que le Portail Patient aussi) envoie ce qui selon le guide CH EMED devrait être un dosage simple, comme split dosage. C’est à dire : pour une posologie p.ex. 0-1-0-1, normalement ça devrait être qu’un élément Dosage avec un champ when contenant NOON, EVE, cependant Presco envoie deux Dosages comme s’il s’agissait du split dosage donc un avec toutes les infos additionnelles pour NOON et un Dosage (split) pour EVE. On devrait discuter si on doit obliger les implémenteurs à respecter le guide CH EMED ou pas. Si les implémenteurs ne respectent pas le guide on doit décider si ou bien c’est le guide qui doit être modifié ou bien on a des bonnes raisons pour obliger les implémenteurs à suivre le guide (p.ex. avec des contraintes dans l’IG ou de règles de validation additionnelles dans Husky). Je n’ai pas créé une issue pour cette discussion. Si on ouvre cette discussion on devra aussi tenir au courant et en compte l’équipe qui maintient et valide CH EMED."

**Comment by iherveOCSIN** [comment]
@dvribeira va partager avec CH EMED le gap existant entre split dosage et simple dosage

**Comment by dvribeira** [comment]
After discussion within CH EMED (present M. Ziegler and Q. Ligier for Ahdis, P. Jolo for ehealthsuisse and myself for the PMP), it was the consensus that implementers should try to use simple dosage whenever possible. To be discussed during this Wednesday's PMP specs meeting at 3pm with implementers.

**Comment by dvribeira** [comment]
After discussion during PMP specs meeting today: implementers should use simple dosage whenever possible. No additional rules to be added to CH-EMED or CH-EMED-EPR on this regard since anyway systems are able to deal with a simple dose presented as a split dose in the content.

Addition of validation rules can be discussed if so desired, but they might become too complex for little limited gain.

**Comment by dejajs** [comment]
this has been implemented on PRESCO side
