### ISSUE TITLE
Incorrect mapping due to missing code

### ISSUE THREAD

**Issue by iherveOCSIN** [CARA-ch/pmp-issues#27]
KAMILLEX and FUCIDIN were imported in Soarian in text format

Response of Olivier Pignolet on Friday 15th march 2024 11:01

The main problem came from the absence of the code “[408102007]” in the mapping; why, to be discussed with Oracle.

![Image](https://github.com/CARA-ch/pmp-issues/assets/158463876/d70c70c2-4b8f-4342-80d7-5e2df96b20a0)

![Image](https://github.com/CARA-ch/pmp-issues/assets/158463876/e83c59e7-52c9-45af-852e-1953a9129fd8)

![Image](https://github.com/CARA-ch/pmp-issues/assets/158463876/45456bb5-380f-4c97-8fb5-6f49c800082c)

![Image](https://github.com/CARA-ch/pmp-issues/assets/158463876/db8245cb-3ad2-41c0-b04f-ef7d8c29dab9)

**Comment by iherveOCSIN** [comment]
en cours de résolution, liste interne à mettre à jour

**Comment by CheriGey** [comment]
The Soarian tools have been updated to align with the Unit Code changes and sent CHUV to make their changes.

**Comment by CheriGey** [comment]
CHUV successfully tested the mapping update.  Closing ticket.
