### ISSUE TITLE
"Reason Topiramate" repeated

### ISSUE THREAD

**Issue by iherveOCSIN** [CARA-ch/pmp-issues#28]
![Image](https://github.com/CARA-ch/pmp-issues/assets/158463876/d1e564de-31ac-43bc-8c3c-b7096d68ac64)

**Comment by dejajs** [comment]
homeOrder.comment <-> medicationStatement.note
homeOrder.sideEffects -> medicationStatement.note
homeOrder.stopReason <-> medicaitonStatement.note (status.cancelled)
homeOrder.treatmentReason <-> medicationStatement.reasonCode.text
homeOrder.treatmentReasons <-> medicationStatement.reasonCode.coding

Scénario ou cardinalité des medicationStatement.notes est diminué à 1:
1) On importe medicaitonStatement, toutes les notes vont dans homeOrder.comment.
2) Si PADV depuis ce homeOrder, un seul élément dans l'array medicationStatement.notes avec toutes les valeurs concaténée du medicationStatement importé dans l'étape 1
