### ISSUE TITLE
Update IG: Text, additionalInstruction and patientInstruction fields in Dosage base

### ISSUE THREAD

**Issue by iherveOCSIN** [CARA-ch/pmp-issues#29]
Explanations from @dvribeira 

![Image](https://github.com/CARA-ch/pmp-issues/assets/158463876/7f102ce2-3a65-4187-9355-c112a6f0e390)

**Comment by iherveOCSIN** [comment]
@dejajs @sep-proactive pourriez-vous partager votre avis et si ok, implémenter de votre côté ? Cela permettra à @dvribeira d'avancer et de soumettre à CH EMED

**Comment by dvribeira** [comment]
It would be best to first agree and then I will also discuss the feedback with CH EMED / ehealthsuisse to be sure we are all aligned. If the imlementation of these changes is not trivial to implementers, it would be best to wait to have green light also from CH EMED / ehealthsuisse before actually implementing them.

@dejajs @sep-proactive could you first just tell me if you would agree with what is proposed in the description? We can discuss it on next Wednesday's pmp specs meeting.

@CheriGey Could you please confirm what happens with the content of the base dosage .text when there's split dose? Are you including the narrative that would correspond to the split dosage elements?

Thanks!

**Comment by sep-proactive** [comment]
@dvribeira In our portal, we currently use these fields as follows:

- text : never used
- additionalInstruction : never used
- patientInstruction : used for additional instructions for the patient (for structured dosage) **or** used for instructions on taking (for unstructured dosage)

The difference between 'additionalInstruction' and 'patientInstruction' is not very clear. If my understanding is correct, each of them corresponds to one of the cases we currently have for patientInstruction, so the proposal seems relevant.

For the field 'text', as we don't use it, I don't see the added value in making it mandatory.

In all cases, we don't have strong constraints related to these fields, so we could easily adapt in our application.

**Comment by CheriGey** [comment]
@dvribeira Here is an example of how the split dose text looks.  Coming from a hospital system, the doses are formatted with specific times in the text (not ideal); it also includes fields such as the order duration, future start date, and a dose duration for something like a patch or inhaler (not included with this example). Any unstructured data is also appended to the Patient Instructions.

![image](https://github.com/CARA-ch/pmp-issues/assets/128403443/da22ffab-52f6-4d66-85aa-ac3c45825155)

**Comment by dvribeira** [comment]
After discussion within CH EMED (with M. Ziegler, Q. Ligier and P. Jolo for ehealtsuisse), the consensus was that we should go with the following:

- `text` for full narrative (up to us, I will suggest keeping maybe 0..1 cardinality but adding a warning if not present or blank)
- `patientInstruction`: for all the dosage information that cannot be provided in a structured manner
- `additionalInstruction`: optionally, up to the implementer to add extra dosage information in a coded way, regardless if present in patientInstruction or not. That is: it is _mandatory_ to add any non-structured dosing information to patientInstruction but it is optional to add it to additionalInstruction, which becomes a nice-to-have if the system fancies it.

We will discuss this during this Wednesday's specs meeting at 3pm CET. Whatever is decided in this meeting will be added here and implemented in the IG.

**Comment by dvribeira** [comment]
> After discussion within CH EMED (with M. Ziegler, Q. Ligier and P. Jolo for ehealtsuisse), the consensus was that we should go with the following:
> 
>     * `text` for full narrative (up to us, I will suggest keeping maybe 0..1 cardinality but adding a warning if not present or blank)
> 
>     * `patientInstruction`: for all the dosage information that cannot be provided in a structured manner
> 
>     * `additionalInstruction`: optionally, up to the implementer to add extra dosage information in a coded way, regardless if present in patientInstruction or not. That is: it is _mandatory_ to add any non-structured dosing information to patientInstruction but it is optional to add it to additionalInstruction, which becomes a nice-to-have if the system fancies it.
> 
> 
> We will discuss this during this Wednesday's specs meeting at 3pm CET. Whatever is decided in this meeting will be added here and implemented in the IG.

Proposal accepted in today's PMP specs meeting attendants, here's the issue on ch-emed-epr: https://github.com/CARA-ch/ch-emed-epr/issues/61

Since no extra discussion is needed at this point, and changes to the IG will only be part of the next CH EMED EPR version, I am closing this issue. The CH EMED EPR implementation can be followed in the ch-emed-epr github issue.
