### ISSUE TITLE
Review the cardinality of the medication statement reasonCode?

### ISSUE THREAD

**Issue by dvribeira** [CARA-ch/pmp-issues#32]
After discussion with @dejajs , concerning Presco's mapping of their own treatments, Presco allows specifying several treatment reasons (several coded and one as a free text IIUC), which is not allowed with the current cardinality (constrained by CH EMED to 0..1). The reasons for this predate my arrival to the project so I do not know if there was some reason other than simplicity for this constraint. 

@qligier Do you have any recollection about why `MedicationStatement.reasonCode` has cardinality `0..1` on the MTP document? We can discuss this tomorrow during the PMP specs meeting.

**Comment by qligier** [comment]
I don't know why it was restricted, but I would be inclined to think it was done to have at most one `reasonCode.text`.

**Comment by dvribeira** [comment]
PMP Specs Meeting: O. Egger commented the source of this cardinality constraint was the IPAG domain definition: https://docs.google.com/spreadsheets/d/1Ui3NGFE2I8yiOlHELk-B0Pke2l9-Jbe5BTeYOnS8-uE

Could be reviewed if needed.

The issue has not been further discussed given no person present from affected systems. See meeting notes: https://docs.google.com/document/d/1af-pNhEVU2IbAHV0opZwPCJC0bORCwQOlKG_0oGgwfQ

**Comment by iherveOCSIN** [comment]
@dvribeira To be discussed at the next SPEC meeting (April 24th) for multiple reason code

**Comment by dvribeira** [comment]
After meeting with professionals on 2024.04.30: a request to change the cardinality to 0..* will be submitted.

**Comment by dvribeira** [comment]
CH EMED request: https://github.com/hl7ch/ch-emed/issues/268

**Comment by dvribeira** [comment]
The cardinality has been changed per our request in CH EMED (pending publication of new release) and will be integrated by CH EMED EPR with the next publication (shortly after CH EMED's in principle).
