### ISSUE TITLE
Erreur de type sur quantité de dosage avec décimale

### ISSUE THREAD

**Issue by laberg** [CARA-ch/pmp-issues#37]
#### Description
La liste des traitements n'a pas pu être récupérée sur le portail patient. 
En regardant dans la console, il semble qu'il y ait une erreur de typage sur le champ `medicationStatement.dosage[x].doseAndRate.doseQuantity.value` (https://build.fhir.org/ig/CARA-ch/ch-emed-epr/StructureDefinition-ch-emed-epr-amount-quantity.html). Ce champ est défini en décimal (Numerical value), mais l'erreur semble indiquer que l'agrégateur l'a considéré comme un string et a tenté de le convertir en nombre, soulevant l'exception `java.lang.NumberFormatException`.

#### Screenshots
![image](https://github.com/CARA-ch/pmp-issues/assets/12517975/2c9c9dcd-64ad-4475-8d32-b3470cf879c8)
![image](https://github.com/CARA-ch/pmp-issues/assets/12517975/96508db3-6f7c-4e83-882e-3e169439b8ee)

#### Files
[EPRIK ITI-43 transaction details](https://test.ahdis.ch/eprik-cara/#/transaction/14762e30-8b53-44ba-a690-d4ec347a496e)
[EPRIK PHARM-1 transaction details](https://test.ahdis.ch/eprik-cara/#/transaction/d3476101-1ba0-40c4-914a-10f571c9bbf0)

#### To Reproduce
1. Créer ou mettre à jour sur le PMP un traitement pour le patient en saisissant pour la quantité de dosage un chiffre avec décimal (0.25, 0.5, 0.75) et typé en tant que nombre avant de le publier (comme c'est le cas dans l'app mobile Swiss-Meds)
2. Naviguer sur Chrome à l'adresse [https://test.ahdis.ch/pmp-portal-int/#/login](url)
3. Cliquer sur l'id du patient pour tenter de récupérer sa liste de traitements

#### Tasks
- [ ] Le type de `medicationStatement.dosage[x].doseAndRate.doseQuantity.value` devrait être un chiffre à décimal dans l'agrégateur

**Comment by laberg** [comment]
@dvribeira n'hésite pas à me demander si tu as besoin de plus d'information.

J'ai créé cet issue dans TODO, j'espère que c'est ok.

**Comment by dvribeira** [comment]
Je viens de récupérer le PMLC du patient SWISSMEDS001 en INT et j'ai vérifié que le contenu retourné par l'agrégateur est correct:
![imagem](https://github.com/CARA-ch/pmp-issues/assets/133101442/c8a59041-7084-471f-89cb-2323b6eb05d0)
Donc si quelqu'un d'autre n'arrive pas a reproduire le problème dans un autre système je le considérerai un bug du portail patient. Peut-être il s'agit d'un bug dans husky, mais je ne peut pas faire le debug du portail.

**Comment by dvribeira** [comment]
Aussi, le lien EPRIK fourni c'est pour la requête PHARM-1 qui ne retourne pas le contenu du PMLC, ça serait la ITI-43 suivant la PHARM-1.

**Comment by laberg** [comment]
> Aussi, le lien EPRIK fourni c'est pour la requête PHARM-1 qui ne retourne pas le contenu du PMLC, ça serait la ITI-43 suivant la PHARM-1.

J'ai rajouté le lien vers l'ITI-43

**Comment by dvribeira** [comment]
Merci @laberg !

Dans la réponse sur le lien EPRIK on peut constater aussi que les valeurs `0.5` sont numériques comme attendu.

**Comment by qligier** [comment]
Effectivement, bug dans le portail patient. Je vais corriger ça.

**Comment by qligier** [comment]
Corrigé dans la dernière version, déployé sur pmp-portal-dev
