### ISSUE TITLE
User can't change dosage

### ISSUE THREAD

**Issue by iherveOCSIN** [CARA-ch/pmp-issues#7]
**Relié à la user story #3** 

L'utilisateur ne peut pas changer la posologie d'un médicament déjà ajouté au préalable.

PADV Change: une erreur apparaît de notre côté, car la voie d’administration (RouteOfAdministration/route) ne figure pas dans les données reçues (PMLC) et ne peut donc pas être utilisée lors de l’envoi du PADV.

**Comment by iherveOCSIN** [comment]
#3

**Comment by sep-proactive** [comment]
Issue fixed
